---
title: "Plots"
author: "Miguel Blanco"
format: html
editor: visual
---

#### Total death per age_group barplot

```{r}
mortality_summary <- data_clean |> 
  group_by(`Age_ranges[years]`, Death) |> 
  summarise(Count = n()) |>
  mutate(`Age_ranges[years]` = factor(`Age_ranges[years]`, levels = c("<60", "60-70", "70-80","80-90", ">90"))) |> 
  mutate(Percentage = round((Count/ sum(Count)) * 100, digits = 1)) |> 
  ungroup()
```

#### Death rate per age_group barplot

```{r}
ggplot(mortality_summary, 
       mapping = aes( x= `Age_ranges[years]`, y = Count, fill = Death))+
  geom_bar(stat = "identity", position = "dodge")+
  scale_fill_manual(
    values = c("0" = "blue", "1" = "red"),
    labels = c("0" = "Survived", "1" = "Dead")
  )+
  labs(
    title = "Mortality per age group",
    fill = "Outcome",
    x = "Age Groups"
  )+
  theme_minimal()+
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

```

### Death rate per Age_group (Percentage)

```{r}
ggplot(mortality_summary, 
       mapping = aes( x= `Age_ranges[years]`, y = Percentage, fill = Death))+
  geom_bar(stat = "identity", position = "dodge")+
  scale_fill_manual(
    values = c("0" = "blue", "1" = "red"),
    labels = c("0" = "Survived", "1" = "Dead")
  )+
  labs(
    title = "Mortality Rate per age group",
    fill = "Outcome",
    x = "Age Groups",
    y = "%"
  )+
  theme_minimal()+
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```

### Hospitalization time per Outcome (Boxplot)

```{r}
ggplot(data = data_clean,
       mapping = aes(x = Death,
                     y = `Hospitalization_time[days]`,
                     fill = Death))+
  geom_boxplot()+
  scale_fill_manual(
    labels = c("0" = "Survive", "1" = "Died"),
    values = c("0" = "blue", "1" = "red"))+
  labs(
    title = "Death Vs Hospitalization Time Boxplot",
    x = "Outcome",
    y = "Hospitalization Time"
  )+
  theme_minimal()+
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```

### Hospitalization time per Outcome (Density plot)

```{r}
ggplot(data = data_clean,
       mapping = aes(x = `Hospitalization_time[days]`,
                     fill = Death))+
  geom_density(alpha = 0.5)+
  scale_fill_manual(
    labels = c("0" = "Survive", "1" = "Died"),
    values = c("0" = "blue", "1" = "red"))+
  labs(
    title = "Death Vs Hospitalization Time Boxplot",
    x = "Hospitalization Time",
    y = "Density"
  )+
  theme_minimal()+
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```

```{r}
#Plot Charlson index vs age range
ggplot(data = data_clean,
             mapping = aes(x = `Age_range`,
                           y = `Charlson index[score]`))+
  geom_boxplot(fill = "skyblue", color = "black")+
  labs(
     title = "Charlson Index by Age Range",
      x = "Age Range",
      y = "Charlson Index Score",
  )+
  theme_minimal()
```

```{r}
#Plot Hospitalization time vs Age range
ggplot(data = data_clean, 
             mapping = aes(x = `Age_range`,
                           y = `Hospitalization time[days]`))+
  geom_boxplot(fill = "skyblue", color = "black")+
  labs(
    title = "Hospitalization time vs age group",
    x = "Age group",
    y = "Hospitalization days"
  )+
  theme_minimal()
```

```{r}
#Plot Hospitalization time vs Affected lung lobes
P1.a <- ggplot(data = data_clean |> 
                 filter(!is.na(`Affected lung lobes 1`)),
             mapping = aes(x = `Affected lung lobes 1`,
                           y = `Hospitalization time[days]`))+
  geom_boxplot(fill = "skyblue", color = "black")+
  theme_minimal()+
  labs(
    title = "Affected lung lobes 1",
    x = "Affected lung lobes",
    y = "Hospitalization time"
  )
P1.b <- ggplot(data = data_clean |> 
                 filter(!is.na(`Affected lung lobes 2`)),
             mapping = aes(x = `Affected lung lobes 2`,
                           y = `Hospitalization time[days]`))+
  geom_boxplot(fill = "red", color = "black")+
  theme_minimal()+
  labs(
    title = "Affected lung lobes 2",
    x = "Affected lung lobes",
    y = "Hospitalization time"
  )
library("patchwork")
P1.a + P1.b + 
  plot_annotation(
    title = "Hospitalization time by affected lung lobes")
```
