---
title: "Project"
author: "Miguel Blanco"
format: html
editor: visual
---

### Load libraries

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
```

Load Datas

```{r}
data <- read_excel("Project/Clinical_Data_of_COVID-19_Infected_Patients.xlsx", sheet = 1)
```

Change values \[null\] for NAs

```{r}

#Notice that na_if function has to work with the same type of values at the time. For example in this df we have both character and numeric values, so we have to do it in 2 times
data <- data |> 
  mutate(across(where(is.character), ~ na_if(. , "[null]")))
```

Proportions of NA in each column

```{r}
NA_proportions <- data |>
  select(where(anyNA)) |> 
  summarise(across(everything(), ~ mean(is.na(.)), .names = "{col}")) |> 
  #Pivot longer so we can then filter
  pivot_longer(everything(), values_to = "na_proportion", names_to = "column")

NA_proportions
```

Choose columns with more than half of NA values

```{r}
view(NA_proportions |> 
  filter(na_proportion > 0.35))
```

```{r}
nrow(data)
```

Change dirty columns with multiple values to clean binary columns

```{r}
#Change name to a shorter one for sintax conveniance
data_clean <- data |> 
  rename(Basic_diseases = `Basic diseases (1 hypertension, 2 diabetes, 3 cardiovascular diseases, 4 cerebrovascular diseases, 5 COPD, 6 immunodeficiency (such as AIDS, hormone, immunosuppressant use history), 7 malignant tumor, 8 other 9 chronic kidney disease`)
```

```{r}
#Create one column for each of the possible illnesess
data_clean <- data_clean |> 
  mutate(Hypertension = Basic_diseases,
         Diabetes = Basic_diseases,
         CVD = Basic_diseases,
         Cerebrovascular = Basic_diseases,
         COPD = Basic_diseases,
         Inmunodeficiency = Basic_diseases,
         Malignant_tumor = Basic_diseases,
         Other = Basic_diseases,
         Chronic_Kidney = Basic_diseases)
```

```{r}
#For each of the created columns, we do a case_when the number of that illness is detected in the observation, the observation gets a value of 1 (has the illness), otherwise gets a 0 (doesn´t have the illness)
data_clean <- data_clean |> 
  mutate(Hypertension = case_when(str_detect(Hypertension, "1") ~ 1,
                                  is.na(Hypertension) ~ NA,
                                  TRUE ~ 0),
         Diabetes = case_when(str_detect(Diabetes, "2") ~ 1,
                              is.na(Hypertension) ~ NA,
                                  TRUE ~ 0),
         CVD = case_when(str_detect(CVD, "3") ~ 1,
                         is.na(Hypertension) ~ NA,
                                  TRUE ~ 0),
         Cerebrovascular = case_when(str_detect(Cerebrovascular, "4") ~ 1,
                                     is.na(Hypertension) ~ NA,
                                  TRUE ~ 0),
         COPD = case_when(str_detect(COPD, "5") ~ 1,
                          is.na(Hypertension) ~ NA,
                                  TRUE ~ 0),
         Inmunodeficiency = case_when(str_detect(Inmunodeficiency, "6") ~ 1,
                                      is.na(Hypertension) ~ NA,
                                  TRUE ~ 0),
         Malignant_tumor = case_when(str_detect(Malignant_tumor, "7") ~ 1,
                                     is.na(Hypertension) ~ NA,
                                  TRUE ~ 0),
         Other = case_when(str_detect(Other, "8") ~ 1,
                           is.na(Hypertension) ~ NA,
                                  TRUE ~ 0),
         Chronic_Kidney = case_when(str_detect(Chronic_Kidney, "9") ~ 1,
                                    is.na(Hypertension) ~ NA,
                                  TRUE ~ 0)) |> 
  select(-Basic_diseases)

```
